In [2]:
import numpy as np

In [6]:
array1D = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
print(array1D[0])

1


In [11]:
array1D_1=(["Hello", 1 , 2])
print(array1D_1[0])

Hello


In [22]:
array2D = np.array([["Hello", "Welcome", "Dear", "Morning"], ["Karthi", "Gayathiri", "Yazh", "Venba"]])

In [23]:
print(array2D[0,2], array2D[1,1])

Dear Gayathiri


In [25]:
array3D = np.array([[["Hello", "Welcome", "Dear", "Morning"], ["Karthi", "Gayathiri", "Yazh", "Venba"], [1,2,3,4]]])

In [29]:
array3D.ndim
array3D

array([[['Hello', 'Welcome', 'Dear', 'Morning'],
        ['Karthi', 'Gayathiri', 'Yazh', 'Venba'],
        ['1', '2', '3', '4']]], dtype='<U21')

In [43]:
print(array3D[0,1,-1])

Venba


In [45]:
array4D = np.array([[[["Hello", "Welcome", "Dear", "Morning"], ["Karthi", "Gayathiri", "Yazh", "Venba"], [1,2,3,4]]]])

In [46]:
array4D.ndim
array4D

array([[[['Hello', 'Welcome', 'Dear', 'Morning'],
         ['Karthi', 'Gayathiri', 'Yazh', 'Venba'],
         ['1', '2', '3', '4']]]], dtype='<U21')

In [49]:
print(array4D[0,-1,0,1])

Welcome


In [54]:
zeroes = np.zeros((3,3,3,3,3,3,3,3), dtype=int)

print(zeroes)

[[[[[[[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]


     [[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]


     [[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]]



    [[[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]


     [[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]


     [[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]]]



    [[[[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]]

      [[0 0 0]
       [0 0 0]
       [0 0 0]

In [56]:
no = np.full((3,3), 8, dtype=int)

print(no)

[[8 8 8]
 [8 8 8]
 [8 8 8]]
